[package]
name = "drover"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22.1"
libc = "0.2.174"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["preserve_order"] }

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
